[package]
name = "wifi"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-svc = { version = "0.49.1", default-features = false, features = [
    "std",
] }
log = { version = "0.4.22", default-features = false }
futures-lite = "2.3.0"
